webtalk_init -webtalk_dir C:\\git_repos\\hackster\\Zybo_EV_Platform\\vitis_workspace\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-12-08 22:36:30" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "176032993_1777485347_210642998_121" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "u8lmi5cqticapi29bmlqrso8j9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.074 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1575827800126" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key project_type -value "sdk" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key processor -value "ps7_cortexa9" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key runtime -value "cpp" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key template -value "sdk" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key platform_type -value "NA" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key application_type -value "application" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key device_family -value "NA" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key fpga -value "7z020" -context "vitis\\\\application/1575827800126"
webtalk_add_data -client vitis -key uid -value "NA" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key RecordType -value "ToolUsage" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key BOOTGEN_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key FLASH_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key MOVE_APP_TO_SYSTEM_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key SDX_EXPORT_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key SDX_IMPORT_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key SDX_BUILD_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key SDX_NO_OP_BUILD_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key TCF_APP_DEBUG_count -value "31" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key TCF_SYSTEM_DEBUG_count -value "31" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key GDB_DEBUG_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key QEMU_DEBUG_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key ESTIMATION_DEBUG_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key SDSOC_TRACE_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key PERFORMANCE_ANALYSIS_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key SPM_ANALYSIS_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key CROSS_TRIGGER_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key TCF_PROFILER_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key APPLICATION_PLATFORM_CHANGE_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key APPLICATION_SYS_CONFIG_CHANGE_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_add_data -client vitis -key SYSTEM_PLATFORM_CHANGE_count -value "0" -context "vitis\\\\tool/1575844590446"
webtalk_transmit -clientid 3651457250 -regid "176032993_1777485347_210642998_121" -xml C:\\git_repos\\hackster\\Zybo_EV_Platform\\vitis_workspace\\webtalk\\usage_statistics_ext_vitis.xml -html C:\\git_repos\\hackster\\Zybo_EV_Platform\\vitis_workspace\\webtalk\\usage_statistics_ext_vitis.html -wdm C:\\git_repos\\hackster\\Zybo_EV_Platform\\vitis_workspace\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
