-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity audio_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    AudioA_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    AudioA_TVALID : IN STD_LOGIC;
    AudioA_TREADY : OUT STD_LOGIC;
    AudioA_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    AudioA_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    AudioA_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    AudioA_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    AudioA_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    AudioA_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    AudioB_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    AudioB_TVALID : OUT STD_LOGIC;
    AudioB_TREADY : IN STD_LOGIC;
    AudioB_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    AudioB_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    AudioB_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    AudioB_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    AudioB_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    AudioB_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of audio_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "audio_top,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-3,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=235,HLS_SYN_LUT=543,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal AudioA_V_data_V_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal AudioA_V_data_V_0_vld_in : STD_LOGIC;
    signal AudioA_V_data_V_0_vld_out : STD_LOGIC;
    signal AudioA_V_data_V_0_ack_in : STD_LOGIC;
    signal AudioA_V_data_V_0_ack_out : STD_LOGIC;
    signal AudioA_V_data_V_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal AudioA_V_data_V_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal AudioA_V_data_V_0_sel_rd : STD_LOGIC := '0';
    signal AudioA_V_data_V_0_sel_wr : STD_LOGIC := '0';
    signal AudioA_V_data_V_0_sel : STD_LOGIC;
    signal AudioA_V_data_V_0_load_A : STD_LOGIC;
    signal AudioA_V_data_V_0_load_B : STD_LOGIC;
    signal AudioA_V_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioA_V_data_V_0_state_cmp_full : STD_LOGIC;
    signal AudioA_V_keep_V_0_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioA_V_keep_V_0_vld_in : STD_LOGIC;
    signal AudioA_V_keep_V_0_vld_out : STD_LOGIC;
    signal AudioA_V_keep_V_0_ack_in : STD_LOGIC;
    signal AudioA_V_keep_V_0_ack_out : STD_LOGIC;
    signal AudioA_V_keep_V_0_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioA_V_keep_V_0_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioA_V_keep_V_0_sel_rd : STD_LOGIC := '0';
    signal AudioA_V_keep_V_0_sel_wr : STD_LOGIC := '0';
    signal AudioA_V_keep_V_0_sel : STD_LOGIC;
    signal AudioA_V_keep_V_0_load_A : STD_LOGIC;
    signal AudioA_V_keep_V_0_load_B : STD_LOGIC;
    signal AudioA_V_keep_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioA_V_keep_V_0_state_cmp_full : STD_LOGIC;
    signal AudioA_V_strb_V_0_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioA_V_strb_V_0_vld_in : STD_LOGIC;
    signal AudioA_V_strb_V_0_vld_out : STD_LOGIC;
    signal AudioA_V_strb_V_0_ack_in : STD_LOGIC;
    signal AudioA_V_strb_V_0_ack_out : STD_LOGIC;
    signal AudioA_V_strb_V_0_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioA_V_strb_V_0_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioA_V_strb_V_0_sel_rd : STD_LOGIC := '0';
    signal AudioA_V_strb_V_0_sel_wr : STD_LOGIC := '0';
    signal AudioA_V_strb_V_0_sel : STD_LOGIC;
    signal AudioA_V_strb_V_0_load_A : STD_LOGIC;
    signal AudioA_V_strb_V_0_load_B : STD_LOGIC;
    signal AudioA_V_strb_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioA_V_strb_V_0_state_cmp_full : STD_LOGIC;
    signal AudioA_V_user_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_user_V_0_vld_in : STD_LOGIC;
    signal AudioA_V_user_V_0_vld_out : STD_LOGIC;
    signal AudioA_V_user_V_0_ack_in : STD_LOGIC;
    signal AudioA_V_user_V_0_ack_out : STD_LOGIC;
    signal AudioA_V_user_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_user_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_user_V_0_sel_rd : STD_LOGIC := '0';
    signal AudioA_V_user_V_0_sel_wr : STD_LOGIC := '0';
    signal AudioA_V_user_V_0_sel : STD_LOGIC;
    signal AudioA_V_user_V_0_load_A : STD_LOGIC;
    signal AudioA_V_user_V_0_load_B : STD_LOGIC;
    signal AudioA_V_user_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioA_V_user_V_0_state_cmp_full : STD_LOGIC;
    signal AudioA_V_last_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_last_V_0_vld_in : STD_LOGIC;
    signal AudioA_V_last_V_0_vld_out : STD_LOGIC;
    signal AudioA_V_last_V_0_ack_in : STD_LOGIC;
    signal AudioA_V_last_V_0_ack_out : STD_LOGIC;
    signal AudioA_V_last_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_last_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_last_V_0_sel_rd : STD_LOGIC := '0';
    signal AudioA_V_last_V_0_sel_wr : STD_LOGIC := '0';
    signal AudioA_V_last_V_0_sel : STD_LOGIC;
    signal AudioA_V_last_V_0_load_A : STD_LOGIC;
    signal AudioA_V_last_V_0_load_B : STD_LOGIC;
    signal AudioA_V_last_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioA_V_last_V_0_state_cmp_full : STD_LOGIC;
    signal AudioA_V_id_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_id_V_0_vld_in : STD_LOGIC;
    signal AudioA_V_id_V_0_vld_out : STD_LOGIC;
    signal AudioA_V_id_V_0_ack_in : STD_LOGIC;
    signal AudioA_V_id_V_0_ack_out : STD_LOGIC;
    signal AudioA_V_id_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_id_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_id_V_0_sel_rd : STD_LOGIC := '0';
    signal AudioA_V_id_V_0_sel_wr : STD_LOGIC := '0';
    signal AudioA_V_id_V_0_sel : STD_LOGIC;
    signal AudioA_V_id_V_0_load_A : STD_LOGIC;
    signal AudioA_V_id_V_0_load_B : STD_LOGIC;
    signal AudioA_V_id_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioA_V_id_V_0_state_cmp_full : STD_LOGIC;
    signal AudioA_V_dest_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_dest_V_0_vld_in : STD_LOGIC;
    signal AudioA_V_dest_V_0_vld_out : STD_LOGIC;
    signal AudioA_V_dest_V_0_ack_in : STD_LOGIC;
    signal AudioA_V_dest_V_0_ack_out : STD_LOGIC;
    signal AudioA_V_dest_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_dest_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioA_V_dest_V_0_sel_rd : STD_LOGIC := '0';
    signal AudioA_V_dest_V_0_sel_wr : STD_LOGIC := '0';
    signal AudioA_V_dest_V_0_sel : STD_LOGIC;
    signal AudioA_V_dest_V_0_load_A : STD_LOGIC;
    signal AudioA_V_dest_V_0_load_B : STD_LOGIC;
    signal AudioA_V_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioA_V_dest_V_0_state_cmp_full : STD_LOGIC;
    signal AudioB_V_data_V_1_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal AudioB_V_data_V_1_vld_in : STD_LOGIC;
    signal AudioB_V_data_V_1_vld_out : STD_LOGIC;
    signal AudioB_V_data_V_1_ack_in : STD_LOGIC;
    signal AudioB_V_data_V_1_ack_out : STD_LOGIC;
    signal AudioB_V_data_V_1_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal AudioB_V_data_V_1_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal AudioB_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal AudioB_V_data_V_1_sel_wr : STD_LOGIC := '0';
    signal AudioB_V_data_V_1_sel : STD_LOGIC;
    signal AudioB_V_data_V_1_load_A : STD_LOGIC;
    signal AudioB_V_data_V_1_load_B : STD_LOGIC;
    signal AudioB_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioB_V_data_V_1_state_cmp_full : STD_LOGIC;
    signal AudioB_V_keep_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioB_V_keep_V_1_vld_in : STD_LOGIC;
    signal AudioB_V_keep_V_1_vld_out : STD_LOGIC;
    signal AudioB_V_keep_V_1_ack_in : STD_LOGIC;
    signal AudioB_V_keep_V_1_ack_out : STD_LOGIC;
    signal AudioB_V_keep_V_1_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioB_V_keep_V_1_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioB_V_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal AudioB_V_keep_V_1_sel_wr : STD_LOGIC := '0';
    signal AudioB_V_keep_V_1_sel : STD_LOGIC;
    signal AudioB_V_keep_V_1_load_A : STD_LOGIC;
    signal AudioB_V_keep_V_1_load_B : STD_LOGIC;
    signal AudioB_V_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioB_V_keep_V_1_state_cmp_full : STD_LOGIC;
    signal AudioB_V_strb_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioB_V_strb_V_1_vld_in : STD_LOGIC;
    signal AudioB_V_strb_V_1_vld_out : STD_LOGIC;
    signal AudioB_V_strb_V_1_ack_in : STD_LOGIC;
    signal AudioB_V_strb_V_1_ack_out : STD_LOGIC;
    signal AudioB_V_strb_V_1_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioB_V_strb_V_1_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal AudioB_V_strb_V_1_sel_rd : STD_LOGIC := '0';
    signal AudioB_V_strb_V_1_sel_wr : STD_LOGIC := '0';
    signal AudioB_V_strb_V_1_sel : STD_LOGIC;
    signal AudioB_V_strb_V_1_load_A : STD_LOGIC;
    signal AudioB_V_strb_V_1_load_B : STD_LOGIC;
    signal AudioB_V_strb_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioB_V_strb_V_1_state_cmp_full : STD_LOGIC;
    signal AudioB_V_user_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_user_V_1_vld_in : STD_LOGIC;
    signal AudioB_V_user_V_1_vld_out : STD_LOGIC;
    signal AudioB_V_user_V_1_ack_in : STD_LOGIC;
    signal AudioB_V_user_V_1_ack_out : STD_LOGIC;
    signal AudioB_V_user_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_user_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_user_V_1_sel_rd : STD_LOGIC := '0';
    signal AudioB_V_user_V_1_sel_wr : STD_LOGIC := '0';
    signal AudioB_V_user_V_1_sel : STD_LOGIC;
    signal AudioB_V_user_V_1_load_A : STD_LOGIC;
    signal AudioB_V_user_V_1_load_B : STD_LOGIC;
    signal AudioB_V_user_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioB_V_user_V_1_state_cmp_full : STD_LOGIC;
    signal AudioB_V_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_last_V_1_vld_in : STD_LOGIC;
    signal AudioB_V_last_V_1_vld_out : STD_LOGIC;
    signal AudioB_V_last_V_1_ack_in : STD_LOGIC;
    signal AudioB_V_last_V_1_ack_out : STD_LOGIC;
    signal AudioB_V_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_last_V_1_sel_rd : STD_LOGIC := '0';
    signal AudioB_V_last_V_1_sel_wr : STD_LOGIC := '0';
    signal AudioB_V_last_V_1_sel : STD_LOGIC;
    signal AudioB_V_last_V_1_load_A : STD_LOGIC;
    signal AudioB_V_last_V_1_load_B : STD_LOGIC;
    signal AudioB_V_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioB_V_last_V_1_state_cmp_full : STD_LOGIC;
    signal AudioB_V_id_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_id_V_1_vld_in : STD_LOGIC;
    signal AudioB_V_id_V_1_vld_out : STD_LOGIC;
    signal AudioB_V_id_V_1_ack_in : STD_LOGIC;
    signal AudioB_V_id_V_1_ack_out : STD_LOGIC;
    signal AudioB_V_id_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_id_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_id_V_1_sel_rd : STD_LOGIC := '0';
    signal AudioB_V_id_V_1_sel_wr : STD_LOGIC := '0';
    signal AudioB_V_id_V_1_sel : STD_LOGIC;
    signal AudioB_V_id_V_1_load_A : STD_LOGIC;
    signal AudioB_V_id_V_1_load_B : STD_LOGIC;
    signal AudioB_V_id_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioB_V_id_V_1_state_cmp_full : STD_LOGIC;
    signal AudioB_V_dest_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_dest_V_1_vld_in : STD_LOGIC;
    signal AudioB_V_dest_V_1_vld_out : STD_LOGIC;
    signal AudioB_V_dest_V_1_ack_in : STD_LOGIC;
    signal AudioB_V_dest_V_1_ack_out : STD_LOGIC;
    signal AudioB_V_dest_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_dest_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal AudioB_V_dest_V_1_sel_rd : STD_LOGIC := '0';
    signal AudioB_V_dest_V_1_sel_wr : STD_LOGIC := '0';
    signal AudioB_V_dest_V_1_sel : STD_LOGIC;
    signal AudioB_V_dest_V_1_load_A : STD_LOGIC;
    signal AudioB_V_dest_V_1_load_B : STD_LOGIC;
    signal AudioB_V_dest_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AudioB_V_dest_V_1_state_cmp_full : STD_LOGIC;
    signal AudioA_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal AudioB_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    AudioA_V_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_data_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_data_V_0_vld_out))) then 
                                        AudioA_V_data_V_0_sel_rd <= not(AudioA_V_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_data_V_0_ack_in) and (ap_const_logic_1 = AudioA_V_data_V_0_vld_in))) then 
                                        AudioA_V_data_V_0_sel_wr <= not(AudioA_V_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioA_V_data_V_0_state) and (ap_const_logic_0 = AudioA_V_data_V_0_vld_in)) or ((ap_const_lv2_3 = AudioA_V_data_V_0_state) and (ap_const_logic_0 = AudioA_V_data_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_data_V_0_ack_out)))) then 
                    AudioA_V_data_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioA_V_data_V_0_state) and (ap_const_logic_0 = AudioA_V_data_V_0_ack_out)) or ((ap_const_lv2_3 = AudioA_V_data_V_0_state) and (ap_const_logic_0 = AudioA_V_data_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_data_V_0_vld_in)))) then 
                    AudioA_V_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioA_V_data_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_data_V_0_ack_out))) and not(((ap_const_logic_0 = AudioA_V_data_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_data_V_0_vld_in))) and (ap_const_lv2_3 = AudioA_V_data_V_0_state)) or ((ap_const_lv2_1 = AudioA_V_data_V_0_state) and (ap_const_logic_1 = AudioA_V_data_V_0_ack_out)) or ((ap_const_lv2_2 = AudioA_V_data_V_0_state) and (ap_const_logic_1 = AudioA_V_data_V_0_vld_in)))) then 
                    AudioA_V_data_V_0_state <= ap_const_lv2_3;
                else 
                    AudioA_V_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_dest_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_dest_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_dest_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_dest_V_0_vld_out))) then 
                                        AudioA_V_dest_V_0_sel_rd <= not(AudioA_V_dest_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_dest_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_dest_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_dest_V_0_ack_in) and (ap_const_logic_1 = AudioA_V_dest_V_0_vld_in))) then 
                                        AudioA_V_dest_V_0_sel_wr <= not(AudioA_V_dest_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioA_V_dest_V_0_state) and (ap_const_logic_0 = AudioA_V_dest_V_0_vld_in)) or ((ap_const_lv2_3 = AudioA_V_dest_V_0_state) and (ap_const_logic_0 = AudioA_V_dest_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_dest_V_0_ack_out)))) then 
                    AudioA_V_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioA_V_dest_V_0_state) and (ap_const_logic_0 = AudioA_V_dest_V_0_ack_out)) or ((ap_const_lv2_3 = AudioA_V_dest_V_0_state) and (ap_const_logic_0 = AudioA_V_dest_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_dest_V_0_vld_in)))) then 
                    AudioA_V_dest_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioA_V_dest_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_dest_V_0_ack_out))) and not(((ap_const_logic_0 = AudioA_V_dest_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_dest_V_0_vld_in))) and (ap_const_lv2_3 = AudioA_V_dest_V_0_state)) or ((ap_const_lv2_1 = AudioA_V_dest_V_0_state) and (ap_const_logic_1 = AudioA_V_dest_V_0_ack_out)) or ((ap_const_lv2_2 = AudioA_V_dest_V_0_state) and (ap_const_logic_1 = AudioA_V_dest_V_0_vld_in)))) then 
                    AudioA_V_dest_V_0_state <= ap_const_lv2_3;
                else 
                    AudioA_V_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_id_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_id_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_id_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_id_V_0_vld_out))) then 
                                        AudioA_V_id_V_0_sel_rd <= not(AudioA_V_id_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_id_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_id_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_id_V_0_ack_in) and (ap_const_logic_1 = AudioA_V_id_V_0_vld_in))) then 
                                        AudioA_V_id_V_0_sel_wr <= not(AudioA_V_id_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_id_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_id_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioA_V_id_V_0_state) and (ap_const_logic_0 = AudioA_V_id_V_0_vld_in)) or ((ap_const_lv2_3 = AudioA_V_id_V_0_state) and (ap_const_logic_0 = AudioA_V_id_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_id_V_0_ack_out)))) then 
                    AudioA_V_id_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioA_V_id_V_0_state) and (ap_const_logic_0 = AudioA_V_id_V_0_ack_out)) or ((ap_const_lv2_3 = AudioA_V_id_V_0_state) and (ap_const_logic_0 = AudioA_V_id_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_id_V_0_vld_in)))) then 
                    AudioA_V_id_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioA_V_id_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_id_V_0_ack_out))) and not(((ap_const_logic_0 = AudioA_V_id_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_id_V_0_vld_in))) and (ap_const_lv2_3 = AudioA_V_id_V_0_state)) or ((ap_const_lv2_1 = AudioA_V_id_V_0_state) and (ap_const_logic_1 = AudioA_V_id_V_0_ack_out)) or ((ap_const_lv2_2 = AudioA_V_id_V_0_state) and (ap_const_logic_1 = AudioA_V_id_V_0_vld_in)))) then 
                    AudioA_V_id_V_0_state <= ap_const_lv2_3;
                else 
                    AudioA_V_id_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_keep_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_keep_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_keep_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_keep_V_0_vld_out))) then 
                                        AudioA_V_keep_V_0_sel_rd <= not(AudioA_V_keep_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_keep_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_keep_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_keep_V_0_ack_in) and (ap_const_logic_1 = AudioA_V_keep_V_0_vld_in))) then 
                                        AudioA_V_keep_V_0_sel_wr <= not(AudioA_V_keep_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_keep_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_keep_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioA_V_keep_V_0_state) and (ap_const_logic_0 = AudioA_V_keep_V_0_vld_in)) or ((ap_const_lv2_3 = AudioA_V_keep_V_0_state) and (ap_const_logic_0 = AudioA_V_keep_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_keep_V_0_ack_out)))) then 
                    AudioA_V_keep_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioA_V_keep_V_0_state) and (ap_const_logic_0 = AudioA_V_keep_V_0_ack_out)) or ((ap_const_lv2_3 = AudioA_V_keep_V_0_state) and (ap_const_logic_0 = AudioA_V_keep_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_keep_V_0_vld_in)))) then 
                    AudioA_V_keep_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioA_V_keep_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_keep_V_0_ack_out))) and not(((ap_const_logic_0 = AudioA_V_keep_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_keep_V_0_vld_in))) and (ap_const_lv2_3 = AudioA_V_keep_V_0_state)) or ((ap_const_lv2_1 = AudioA_V_keep_V_0_state) and (ap_const_logic_1 = AudioA_V_keep_V_0_ack_out)) or ((ap_const_lv2_2 = AudioA_V_keep_V_0_state) and (ap_const_logic_1 = AudioA_V_keep_V_0_vld_in)))) then 
                    AudioA_V_keep_V_0_state <= ap_const_lv2_3;
                else 
                    AudioA_V_keep_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_last_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_last_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_last_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_last_V_0_vld_out))) then 
                                        AudioA_V_last_V_0_sel_rd <= not(AudioA_V_last_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_last_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_last_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_last_V_0_ack_in) and (ap_const_logic_1 = AudioA_V_last_V_0_vld_in))) then 
                                        AudioA_V_last_V_0_sel_wr <= not(AudioA_V_last_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_last_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_last_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioA_V_last_V_0_state) and (ap_const_logic_0 = AudioA_V_last_V_0_vld_in)) or ((ap_const_lv2_3 = AudioA_V_last_V_0_state) and (ap_const_logic_0 = AudioA_V_last_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_last_V_0_ack_out)))) then 
                    AudioA_V_last_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioA_V_last_V_0_state) and (ap_const_logic_0 = AudioA_V_last_V_0_ack_out)) or ((ap_const_lv2_3 = AudioA_V_last_V_0_state) and (ap_const_logic_0 = AudioA_V_last_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_last_V_0_vld_in)))) then 
                    AudioA_V_last_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioA_V_last_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_last_V_0_ack_out))) and not(((ap_const_logic_0 = AudioA_V_last_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_last_V_0_vld_in))) and (ap_const_lv2_3 = AudioA_V_last_V_0_state)) or ((ap_const_lv2_1 = AudioA_V_last_V_0_state) and (ap_const_logic_1 = AudioA_V_last_V_0_ack_out)) or ((ap_const_lv2_2 = AudioA_V_last_V_0_state) and (ap_const_logic_1 = AudioA_V_last_V_0_vld_in)))) then 
                    AudioA_V_last_V_0_state <= ap_const_lv2_3;
                else 
                    AudioA_V_last_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_strb_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_strb_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_strb_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_strb_V_0_vld_out))) then 
                                        AudioA_V_strb_V_0_sel_rd <= not(AudioA_V_strb_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_strb_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_strb_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_strb_V_0_ack_in) and (ap_const_logic_1 = AudioA_V_strb_V_0_vld_in))) then 
                                        AudioA_V_strb_V_0_sel_wr <= not(AudioA_V_strb_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_strb_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_strb_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioA_V_strb_V_0_state) and (ap_const_logic_0 = AudioA_V_strb_V_0_vld_in)) or ((ap_const_lv2_3 = AudioA_V_strb_V_0_state) and (ap_const_logic_0 = AudioA_V_strb_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_strb_V_0_ack_out)))) then 
                    AudioA_V_strb_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioA_V_strb_V_0_state) and (ap_const_logic_0 = AudioA_V_strb_V_0_ack_out)) or ((ap_const_lv2_3 = AudioA_V_strb_V_0_state) and (ap_const_logic_0 = AudioA_V_strb_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_strb_V_0_vld_in)))) then 
                    AudioA_V_strb_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioA_V_strb_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_strb_V_0_ack_out))) and not(((ap_const_logic_0 = AudioA_V_strb_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_strb_V_0_vld_in))) and (ap_const_lv2_3 = AudioA_V_strb_V_0_state)) or ((ap_const_lv2_1 = AudioA_V_strb_V_0_state) and (ap_const_logic_1 = AudioA_V_strb_V_0_ack_out)) or ((ap_const_lv2_2 = AudioA_V_strb_V_0_state) and (ap_const_logic_1 = AudioA_V_strb_V_0_vld_in)))) then 
                    AudioA_V_strb_V_0_state <= ap_const_lv2_3;
                else 
                    AudioA_V_strb_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_user_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_user_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_user_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_user_V_0_vld_out))) then 
                                        AudioA_V_user_V_0_sel_rd <= not(AudioA_V_user_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_user_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_user_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioA_V_user_V_0_ack_in) and (ap_const_logic_1 = AudioA_V_user_V_0_vld_in))) then 
                                        AudioA_V_user_V_0_sel_wr <= not(AudioA_V_user_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioA_V_user_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioA_V_user_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioA_V_user_V_0_state) and (ap_const_logic_0 = AudioA_V_user_V_0_vld_in)) or ((ap_const_lv2_3 = AudioA_V_user_V_0_state) and (ap_const_logic_0 = AudioA_V_user_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_user_V_0_ack_out)))) then 
                    AudioA_V_user_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioA_V_user_V_0_state) and (ap_const_logic_0 = AudioA_V_user_V_0_ack_out)) or ((ap_const_lv2_3 = AudioA_V_user_V_0_state) and (ap_const_logic_0 = AudioA_V_user_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_user_V_0_vld_in)))) then 
                    AudioA_V_user_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioA_V_user_V_0_vld_in) and (ap_const_logic_1 = AudioA_V_user_V_0_ack_out))) and not(((ap_const_logic_0 = AudioA_V_user_V_0_ack_out) and (ap_const_logic_1 = AudioA_V_user_V_0_vld_in))) and (ap_const_lv2_3 = AudioA_V_user_V_0_state)) or ((ap_const_lv2_1 = AudioA_V_user_V_0_state) and (ap_const_logic_1 = AudioA_V_user_V_0_ack_out)) or ((ap_const_lv2_2 = AudioA_V_user_V_0_state) and (ap_const_logic_1 = AudioA_V_user_V_0_vld_in)))) then 
                    AudioA_V_user_V_0_state <= ap_const_lv2_3;
                else 
                    AudioA_V_user_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_data_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_data_V_1_vld_out))) then 
                                        AudioB_V_data_V_1_sel_rd <= not(AudioB_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_data_V_1_ack_in) and (ap_const_logic_1 = AudioB_V_data_V_1_vld_in))) then 
                                        AudioB_V_data_V_1_sel_wr <= not(AudioB_V_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioB_V_data_V_1_state) and (ap_const_logic_0 = AudioB_V_data_V_1_vld_in)) or ((ap_const_lv2_3 = AudioB_V_data_V_1_state) and (ap_const_logic_0 = AudioB_V_data_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_data_V_1_ack_out)))) then 
                    AudioB_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioB_V_data_V_1_state) and (ap_const_logic_0 = AudioB_V_data_V_1_ack_out)) or ((ap_const_lv2_3 = AudioB_V_data_V_1_state) and (ap_const_logic_0 = AudioB_V_data_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_data_V_1_vld_in)))) then 
                    AudioB_V_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioB_V_data_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_data_V_1_ack_out))) and not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_data_V_1_vld_in))) and (ap_const_lv2_3 = AudioB_V_data_V_1_state)) or ((ap_const_lv2_1 = AudioB_V_data_V_1_state) and (ap_const_logic_1 = AudioB_V_data_V_1_ack_out)) or ((ap_const_lv2_2 = AudioB_V_data_V_1_state) and (ap_const_logic_1 = AudioB_V_data_V_1_vld_in)))) then 
                    AudioB_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    AudioB_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_dest_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_dest_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_dest_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_dest_V_1_vld_out))) then 
                                        AudioB_V_dest_V_1_sel_rd <= not(AudioB_V_dest_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_dest_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_dest_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_dest_V_1_ack_in) and (ap_const_logic_1 = AudioB_V_dest_V_1_vld_in))) then 
                                        AudioB_V_dest_V_1_sel_wr <= not(AudioB_V_dest_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_dest_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_dest_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioB_V_dest_V_1_state) and (ap_const_logic_0 = AudioB_V_dest_V_1_vld_in)) or ((ap_const_lv2_3 = AudioB_V_dest_V_1_state) and (ap_const_logic_0 = AudioB_V_dest_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_dest_V_1_ack_out)))) then 
                    AudioB_V_dest_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioB_V_dest_V_1_state) and (ap_const_logic_0 = AudioB_V_dest_V_1_ack_out)) or ((ap_const_lv2_3 = AudioB_V_dest_V_1_state) and (ap_const_logic_0 = AudioB_V_dest_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_dest_V_1_vld_in)))) then 
                    AudioB_V_dest_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioB_V_dest_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_dest_V_1_ack_out))) and not(((ap_const_logic_0 = AudioB_V_dest_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_dest_V_1_vld_in))) and (ap_const_lv2_3 = AudioB_V_dest_V_1_state)) or ((ap_const_lv2_1 = AudioB_V_dest_V_1_state) and (ap_const_logic_1 = AudioB_V_dest_V_1_ack_out)) or ((ap_const_lv2_2 = AudioB_V_dest_V_1_state) and (ap_const_logic_1 = AudioB_V_dest_V_1_vld_in)))) then 
                    AudioB_V_dest_V_1_state <= ap_const_lv2_3;
                else 
                    AudioB_V_dest_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_id_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_id_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_id_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_id_V_1_vld_out))) then 
                                        AudioB_V_id_V_1_sel_rd <= not(AudioB_V_id_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_id_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_id_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_id_V_1_ack_in) and (ap_const_logic_1 = AudioB_V_id_V_1_vld_in))) then 
                                        AudioB_V_id_V_1_sel_wr <= not(AudioB_V_id_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_id_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_id_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioB_V_id_V_1_state) and (ap_const_logic_0 = AudioB_V_id_V_1_vld_in)) or ((ap_const_lv2_3 = AudioB_V_id_V_1_state) and (ap_const_logic_0 = AudioB_V_id_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_id_V_1_ack_out)))) then 
                    AudioB_V_id_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioB_V_id_V_1_state) and (ap_const_logic_0 = AudioB_V_id_V_1_ack_out)) or ((ap_const_lv2_3 = AudioB_V_id_V_1_state) and (ap_const_logic_0 = AudioB_V_id_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_id_V_1_vld_in)))) then 
                    AudioB_V_id_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioB_V_id_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_id_V_1_ack_out))) and not(((ap_const_logic_0 = AudioB_V_id_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_id_V_1_vld_in))) and (ap_const_lv2_3 = AudioB_V_id_V_1_state)) or ((ap_const_lv2_1 = AudioB_V_id_V_1_state) and (ap_const_logic_1 = AudioB_V_id_V_1_ack_out)) or ((ap_const_lv2_2 = AudioB_V_id_V_1_state) and (ap_const_logic_1 = AudioB_V_id_V_1_vld_in)))) then 
                    AudioB_V_id_V_1_state <= ap_const_lv2_3;
                else 
                    AudioB_V_id_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_keep_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_keep_V_1_vld_out))) then 
                                        AudioB_V_keep_V_1_sel_rd <= not(AudioB_V_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_keep_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_keep_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_keep_V_1_ack_in) and (ap_const_logic_1 = AudioB_V_keep_V_1_vld_in))) then 
                                        AudioB_V_keep_V_1_sel_wr <= not(AudioB_V_keep_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioB_V_keep_V_1_state) and (ap_const_logic_0 = AudioB_V_keep_V_1_vld_in)) or ((ap_const_lv2_3 = AudioB_V_keep_V_1_state) and (ap_const_logic_0 = AudioB_V_keep_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_keep_V_1_ack_out)))) then 
                    AudioB_V_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioB_V_keep_V_1_state) and (ap_const_logic_0 = AudioB_V_keep_V_1_ack_out)) or ((ap_const_lv2_3 = AudioB_V_keep_V_1_state) and (ap_const_logic_0 = AudioB_V_keep_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_keep_V_1_vld_in)))) then 
                    AudioB_V_keep_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioB_V_keep_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_keep_V_1_ack_out))) and not(((ap_const_logic_0 = AudioB_V_keep_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_keep_V_1_vld_in))) and (ap_const_lv2_3 = AudioB_V_keep_V_1_state)) or ((ap_const_lv2_1 = AudioB_V_keep_V_1_state) and (ap_const_logic_1 = AudioB_V_keep_V_1_ack_out)) or ((ap_const_lv2_2 = AudioB_V_keep_V_1_state) and (ap_const_logic_1 = AudioB_V_keep_V_1_vld_in)))) then 
                    AudioB_V_keep_V_1_state <= ap_const_lv2_3;
                else 
                    AudioB_V_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_last_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_last_V_1_vld_out))) then 
                                        AudioB_V_last_V_1_sel_rd <= not(AudioB_V_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_last_V_1_ack_in) and (ap_const_logic_1 = AudioB_V_last_V_1_vld_in))) then 
                                        AudioB_V_last_V_1_sel_wr <= not(AudioB_V_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioB_V_last_V_1_state) and (ap_const_logic_0 = AudioB_V_last_V_1_vld_in)) or ((ap_const_lv2_3 = AudioB_V_last_V_1_state) and (ap_const_logic_0 = AudioB_V_last_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_last_V_1_ack_out)))) then 
                    AudioB_V_last_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioB_V_last_V_1_state) and (ap_const_logic_0 = AudioB_V_last_V_1_ack_out)) or ((ap_const_lv2_3 = AudioB_V_last_V_1_state) and (ap_const_logic_0 = AudioB_V_last_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_last_V_1_vld_in)))) then 
                    AudioB_V_last_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioB_V_last_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_last_V_1_ack_out))) and not(((ap_const_logic_0 = AudioB_V_last_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_last_V_1_vld_in))) and (ap_const_lv2_3 = AudioB_V_last_V_1_state)) or ((ap_const_lv2_1 = AudioB_V_last_V_1_state) and (ap_const_logic_1 = AudioB_V_last_V_1_ack_out)) or ((ap_const_lv2_2 = AudioB_V_last_V_1_state) and (ap_const_logic_1 = AudioB_V_last_V_1_vld_in)))) then 
                    AudioB_V_last_V_1_state <= ap_const_lv2_3;
                else 
                    AudioB_V_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_strb_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_strb_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_strb_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_strb_V_1_vld_out))) then 
                                        AudioB_V_strb_V_1_sel_rd <= not(AudioB_V_strb_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_strb_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_strb_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_strb_V_1_ack_in) and (ap_const_logic_1 = AudioB_V_strb_V_1_vld_in))) then 
                                        AudioB_V_strb_V_1_sel_wr <= not(AudioB_V_strb_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_strb_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_strb_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioB_V_strb_V_1_state) and (ap_const_logic_0 = AudioB_V_strb_V_1_vld_in)) or ((ap_const_lv2_3 = AudioB_V_strb_V_1_state) and (ap_const_logic_0 = AudioB_V_strb_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_strb_V_1_ack_out)))) then 
                    AudioB_V_strb_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioB_V_strb_V_1_state) and (ap_const_logic_0 = AudioB_V_strb_V_1_ack_out)) or ((ap_const_lv2_3 = AudioB_V_strb_V_1_state) and (ap_const_logic_0 = AudioB_V_strb_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_strb_V_1_vld_in)))) then 
                    AudioB_V_strb_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioB_V_strb_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_strb_V_1_ack_out))) and not(((ap_const_logic_0 = AudioB_V_strb_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_strb_V_1_vld_in))) and (ap_const_lv2_3 = AudioB_V_strb_V_1_state)) or ((ap_const_lv2_1 = AudioB_V_strb_V_1_state) and (ap_const_logic_1 = AudioB_V_strb_V_1_ack_out)) or ((ap_const_lv2_2 = AudioB_V_strb_V_1_state) and (ap_const_logic_1 = AudioB_V_strb_V_1_vld_in)))) then 
                    AudioB_V_strb_V_1_state <= ap_const_lv2_3;
                else 
                    AudioB_V_strb_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_user_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_user_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_user_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_user_V_1_vld_out))) then 
                                        AudioB_V_user_V_1_sel_rd <= not(AudioB_V_user_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_user_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_user_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AudioB_V_user_V_1_ack_in) and (ap_const_logic_1 = AudioB_V_user_V_1_vld_in))) then 
                                        AudioB_V_user_V_1_sel_wr <= not(AudioB_V_user_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AudioB_V_user_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                AudioB_V_user_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AudioB_V_user_V_1_state) and (ap_const_logic_0 = AudioB_V_user_V_1_vld_in)) or ((ap_const_lv2_3 = AudioB_V_user_V_1_state) and (ap_const_logic_0 = AudioB_V_user_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_user_V_1_ack_out)))) then 
                    AudioB_V_user_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AudioB_V_user_V_1_state) and (ap_const_logic_0 = AudioB_V_user_V_1_ack_out)) or ((ap_const_lv2_3 = AudioB_V_user_V_1_state) and (ap_const_logic_0 = AudioB_V_user_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_user_V_1_vld_in)))) then 
                    AudioB_V_user_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AudioB_V_user_V_1_vld_in) and (ap_const_logic_1 = AudioB_V_user_V_1_ack_out))) and not(((ap_const_logic_0 = AudioB_V_user_V_1_ack_out) and (ap_const_logic_1 = AudioB_V_user_V_1_vld_in))) and (ap_const_lv2_3 = AudioB_V_user_V_1_state)) or ((ap_const_lv2_1 = AudioB_V_user_V_1_state) and (ap_const_logic_1 = AudioB_V_user_V_1_ack_out)) or ((ap_const_lv2_2 = AudioB_V_user_V_1_state) and (ap_const_logic_1 = AudioB_V_user_V_1_vld_in)))) then 
                    AudioB_V_user_V_1_state <= ap_const_lv2_3;
                else 
                    AudioB_V_user_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_data_V_0_load_A)) then
                AudioA_V_data_V_0_payload_A <= AudioA_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_data_V_0_load_B)) then
                AudioA_V_data_V_0_payload_B <= AudioA_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_dest_V_0_load_A)) then
                AudioA_V_dest_V_0_payload_A <= AudioA_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_dest_V_0_load_B)) then
                AudioA_V_dest_V_0_payload_B <= AudioA_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_id_V_0_load_A)) then
                AudioA_V_id_V_0_payload_A <= AudioA_TID;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_id_V_0_load_B)) then
                AudioA_V_id_V_0_payload_B <= AudioA_TID;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_keep_V_0_load_A)) then
                AudioA_V_keep_V_0_payload_A <= AudioA_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_keep_V_0_load_B)) then
                AudioA_V_keep_V_0_payload_B <= AudioA_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_last_V_0_load_A)) then
                AudioA_V_last_V_0_payload_A <= AudioA_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_last_V_0_load_B)) then
                AudioA_V_last_V_0_payload_B <= AudioA_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_strb_V_0_load_A)) then
                AudioA_V_strb_V_0_payload_A <= AudioA_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_strb_V_0_load_B)) then
                AudioA_V_strb_V_0_payload_B <= AudioA_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_user_V_0_load_A)) then
                AudioA_V_user_V_0_payload_A <= AudioA_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioA_V_user_V_0_load_B)) then
                AudioA_V_user_V_0_payload_B <= AudioA_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_data_V_1_load_A)) then
                AudioB_V_data_V_1_payload_A <= AudioA_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_data_V_1_load_B)) then
                AudioB_V_data_V_1_payload_B <= AudioA_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_dest_V_1_load_A)) then
                AudioB_V_dest_V_1_payload_A <= AudioA_V_dest_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_dest_V_1_load_B)) then
                AudioB_V_dest_V_1_payload_B <= AudioA_V_dest_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_id_V_1_load_A)) then
                AudioB_V_id_V_1_payload_A <= AudioA_V_id_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_id_V_1_load_B)) then
                AudioB_V_id_V_1_payload_B <= AudioA_V_id_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_keep_V_1_load_A)) then
                AudioB_V_keep_V_1_payload_A <= AudioA_V_keep_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_keep_V_1_load_B)) then
                AudioB_V_keep_V_1_payload_B <= AudioA_V_keep_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_last_V_1_load_A)) then
                AudioB_V_last_V_1_payload_A <= AudioA_V_last_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_last_V_1_load_B)) then
                AudioB_V_last_V_1_payload_B <= AudioA_V_last_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_strb_V_1_load_A)) then
                AudioB_V_strb_V_1_payload_A <= AudioA_V_strb_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_strb_V_1_load_B)) then
                AudioB_V_strb_V_1_payload_B <= AudioA_V_strb_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_user_V_1_load_A)) then
                AudioB_V_user_V_1_payload_A <= AudioA_V_user_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AudioB_V_user_V_1_load_B)) then
                AudioB_V_user_V_1_payload_B <= AudioA_V_user_V_0_data_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = AudioB_V_data_V_1_ack_in) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    AudioA_TDATA_blk_n_assign_proc : process(AudioA_V_data_V_0_state, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            AudioA_TDATA_blk_n <= AudioA_V_data_V_0_state(0);
        else 
            AudioA_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    AudioA_TREADY <= AudioA_V_dest_V_0_state(1);
    AudioA_V_data_V_0_ack_in <= AudioA_V_data_V_0_state(1);

    AudioA_V_data_V_0_ack_out_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioA_V_data_V_0_ack_out <= ap_const_logic_1;
        else 
            AudioA_V_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    AudioA_V_data_V_0_data_out_assign_proc : process(AudioA_V_data_V_0_payload_A, AudioA_V_data_V_0_payload_B, AudioA_V_data_V_0_sel)
    begin
        if ((ap_const_logic_1 = AudioA_V_data_V_0_sel)) then 
            AudioA_V_data_V_0_data_out <= AudioA_V_data_V_0_payload_B;
        else 
            AudioA_V_data_V_0_data_out <= AudioA_V_data_V_0_payload_A;
        end if; 
    end process;

    AudioA_V_data_V_0_load_A <= (not(AudioA_V_data_V_0_sel_wr) and AudioA_V_data_V_0_state_cmp_full);
    AudioA_V_data_V_0_load_B <= (AudioA_V_data_V_0_state_cmp_full and AudioA_V_data_V_0_sel_wr);
    AudioA_V_data_V_0_sel <= AudioA_V_data_V_0_sel_rd;
    AudioA_V_data_V_0_state_cmp_full <= '0' when (AudioA_V_data_V_0_state = ap_const_lv2_1) else '1';
    AudioA_V_data_V_0_vld_in <= AudioA_TVALID;
    AudioA_V_data_V_0_vld_out <= AudioA_V_data_V_0_state(0);
    AudioA_V_dest_V_0_ack_in <= AudioA_V_dest_V_0_state(1);

    AudioA_V_dest_V_0_ack_out_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioA_V_dest_V_0_ack_out <= ap_const_logic_1;
        else 
            AudioA_V_dest_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    AudioA_V_dest_V_0_data_out_assign_proc : process(AudioA_V_dest_V_0_payload_A, AudioA_V_dest_V_0_payload_B, AudioA_V_dest_V_0_sel)
    begin
        if ((ap_const_logic_1 = AudioA_V_dest_V_0_sel)) then 
            AudioA_V_dest_V_0_data_out <= AudioA_V_dest_V_0_payload_B;
        else 
            AudioA_V_dest_V_0_data_out <= AudioA_V_dest_V_0_payload_A;
        end if; 
    end process;

    AudioA_V_dest_V_0_load_A <= (not(AudioA_V_dest_V_0_sel_wr) and AudioA_V_dest_V_0_state_cmp_full);
    AudioA_V_dest_V_0_load_B <= (AudioA_V_dest_V_0_state_cmp_full and AudioA_V_dest_V_0_sel_wr);
    AudioA_V_dest_V_0_sel <= AudioA_V_dest_V_0_sel_rd;
    AudioA_V_dest_V_0_state_cmp_full <= '0' when (AudioA_V_dest_V_0_state = ap_const_lv2_1) else '1';
    AudioA_V_dest_V_0_vld_in <= AudioA_TVALID;
    AudioA_V_dest_V_0_vld_out <= AudioA_V_dest_V_0_state(0);
    AudioA_V_id_V_0_ack_in <= AudioA_V_id_V_0_state(1);

    AudioA_V_id_V_0_ack_out_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioA_V_id_V_0_ack_out <= ap_const_logic_1;
        else 
            AudioA_V_id_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    AudioA_V_id_V_0_data_out_assign_proc : process(AudioA_V_id_V_0_payload_A, AudioA_V_id_V_0_payload_B, AudioA_V_id_V_0_sel)
    begin
        if ((ap_const_logic_1 = AudioA_V_id_V_0_sel)) then 
            AudioA_V_id_V_0_data_out <= AudioA_V_id_V_0_payload_B;
        else 
            AudioA_V_id_V_0_data_out <= AudioA_V_id_V_0_payload_A;
        end if; 
    end process;

    AudioA_V_id_V_0_load_A <= (not(AudioA_V_id_V_0_sel_wr) and AudioA_V_id_V_0_state_cmp_full);
    AudioA_V_id_V_0_load_B <= (AudioA_V_id_V_0_state_cmp_full and AudioA_V_id_V_0_sel_wr);
    AudioA_V_id_V_0_sel <= AudioA_V_id_V_0_sel_rd;
    AudioA_V_id_V_0_state_cmp_full <= '0' when (AudioA_V_id_V_0_state = ap_const_lv2_1) else '1';
    AudioA_V_id_V_0_vld_in <= AudioA_TVALID;
    AudioA_V_id_V_0_vld_out <= AudioA_V_id_V_0_state(0);
    AudioA_V_keep_V_0_ack_in <= AudioA_V_keep_V_0_state(1);

    AudioA_V_keep_V_0_ack_out_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioA_V_keep_V_0_ack_out <= ap_const_logic_1;
        else 
            AudioA_V_keep_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    AudioA_V_keep_V_0_data_out_assign_proc : process(AudioA_V_keep_V_0_payload_A, AudioA_V_keep_V_0_payload_B, AudioA_V_keep_V_0_sel)
    begin
        if ((ap_const_logic_1 = AudioA_V_keep_V_0_sel)) then 
            AudioA_V_keep_V_0_data_out <= AudioA_V_keep_V_0_payload_B;
        else 
            AudioA_V_keep_V_0_data_out <= AudioA_V_keep_V_0_payload_A;
        end if; 
    end process;

    AudioA_V_keep_V_0_load_A <= (not(AudioA_V_keep_V_0_sel_wr) and AudioA_V_keep_V_0_state_cmp_full);
    AudioA_V_keep_V_0_load_B <= (AudioA_V_keep_V_0_state_cmp_full and AudioA_V_keep_V_0_sel_wr);
    AudioA_V_keep_V_0_sel <= AudioA_V_keep_V_0_sel_rd;
    AudioA_V_keep_V_0_state_cmp_full <= '0' when (AudioA_V_keep_V_0_state = ap_const_lv2_1) else '1';
    AudioA_V_keep_V_0_vld_in <= AudioA_TVALID;
    AudioA_V_keep_V_0_vld_out <= AudioA_V_keep_V_0_state(0);
    AudioA_V_last_V_0_ack_in <= AudioA_V_last_V_0_state(1);

    AudioA_V_last_V_0_ack_out_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioA_V_last_V_0_ack_out <= ap_const_logic_1;
        else 
            AudioA_V_last_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    AudioA_V_last_V_0_data_out_assign_proc : process(AudioA_V_last_V_0_payload_A, AudioA_V_last_V_0_payload_B, AudioA_V_last_V_0_sel)
    begin
        if ((ap_const_logic_1 = AudioA_V_last_V_0_sel)) then 
            AudioA_V_last_V_0_data_out <= AudioA_V_last_V_0_payload_B;
        else 
            AudioA_V_last_V_0_data_out <= AudioA_V_last_V_0_payload_A;
        end if; 
    end process;

    AudioA_V_last_V_0_load_A <= (not(AudioA_V_last_V_0_sel_wr) and AudioA_V_last_V_0_state_cmp_full);
    AudioA_V_last_V_0_load_B <= (AudioA_V_last_V_0_state_cmp_full and AudioA_V_last_V_0_sel_wr);
    AudioA_V_last_V_0_sel <= AudioA_V_last_V_0_sel_rd;
    AudioA_V_last_V_0_state_cmp_full <= '0' when (AudioA_V_last_V_0_state = ap_const_lv2_1) else '1';
    AudioA_V_last_V_0_vld_in <= AudioA_TVALID;
    AudioA_V_last_V_0_vld_out <= AudioA_V_last_V_0_state(0);
    AudioA_V_strb_V_0_ack_in <= AudioA_V_strb_V_0_state(1);

    AudioA_V_strb_V_0_ack_out_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioA_V_strb_V_0_ack_out <= ap_const_logic_1;
        else 
            AudioA_V_strb_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    AudioA_V_strb_V_0_data_out_assign_proc : process(AudioA_V_strb_V_0_payload_A, AudioA_V_strb_V_0_payload_B, AudioA_V_strb_V_0_sel)
    begin
        if ((ap_const_logic_1 = AudioA_V_strb_V_0_sel)) then 
            AudioA_V_strb_V_0_data_out <= AudioA_V_strb_V_0_payload_B;
        else 
            AudioA_V_strb_V_0_data_out <= AudioA_V_strb_V_0_payload_A;
        end if; 
    end process;

    AudioA_V_strb_V_0_load_A <= (not(AudioA_V_strb_V_0_sel_wr) and AudioA_V_strb_V_0_state_cmp_full);
    AudioA_V_strb_V_0_load_B <= (AudioA_V_strb_V_0_state_cmp_full and AudioA_V_strb_V_0_sel_wr);
    AudioA_V_strb_V_0_sel <= AudioA_V_strb_V_0_sel_rd;
    AudioA_V_strb_V_0_state_cmp_full <= '0' when (AudioA_V_strb_V_0_state = ap_const_lv2_1) else '1';
    AudioA_V_strb_V_0_vld_in <= AudioA_TVALID;
    AudioA_V_strb_V_0_vld_out <= AudioA_V_strb_V_0_state(0);
    AudioA_V_user_V_0_ack_in <= AudioA_V_user_V_0_state(1);

    AudioA_V_user_V_0_ack_out_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioA_V_user_V_0_ack_out <= ap_const_logic_1;
        else 
            AudioA_V_user_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    AudioA_V_user_V_0_data_out_assign_proc : process(AudioA_V_user_V_0_payload_A, AudioA_V_user_V_0_payload_B, AudioA_V_user_V_0_sel)
    begin
        if ((ap_const_logic_1 = AudioA_V_user_V_0_sel)) then 
            AudioA_V_user_V_0_data_out <= AudioA_V_user_V_0_payload_B;
        else 
            AudioA_V_user_V_0_data_out <= AudioA_V_user_V_0_payload_A;
        end if; 
    end process;

    AudioA_V_user_V_0_load_A <= (not(AudioA_V_user_V_0_sel_wr) and AudioA_V_user_V_0_state_cmp_full);
    AudioA_V_user_V_0_load_B <= (AudioA_V_user_V_0_state_cmp_full and AudioA_V_user_V_0_sel_wr);
    AudioA_V_user_V_0_sel <= AudioA_V_user_V_0_sel_rd;
    AudioA_V_user_V_0_state_cmp_full <= '0' when (AudioA_V_user_V_0_state = ap_const_lv2_1) else '1';
    AudioA_V_user_V_0_vld_in <= AudioA_TVALID;
    AudioA_V_user_V_0_vld_out <= AudioA_V_user_V_0_state(0);
    AudioB_TDATA <= AudioB_V_data_V_1_data_out;

    AudioB_TDATA_blk_n_assign_proc : process(AudioB_V_data_V_1_state, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioB_TDATA_blk_n <= AudioB_V_data_V_1_state(1);
        else 
            AudioB_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    AudioB_TDEST <= AudioB_V_dest_V_1_data_out;
    AudioB_TID <= AudioB_V_id_V_1_data_out;
    AudioB_TKEEP <= AudioB_V_keep_V_1_data_out;
    AudioB_TLAST <= AudioB_V_last_V_1_data_out;
    AudioB_TSTRB <= AudioB_V_strb_V_1_data_out;
    AudioB_TUSER <= AudioB_V_user_V_1_data_out;
    AudioB_TVALID <= AudioB_V_dest_V_1_state(0);
    AudioB_V_data_V_1_ack_in <= AudioB_V_data_V_1_state(1);
    AudioB_V_data_V_1_ack_out <= AudioB_TREADY;

    AudioB_V_data_V_1_data_out_assign_proc : process(AudioB_V_data_V_1_payload_A, AudioB_V_data_V_1_payload_B, AudioB_V_data_V_1_sel)
    begin
        if ((ap_const_logic_1 = AudioB_V_data_V_1_sel)) then 
            AudioB_V_data_V_1_data_out <= AudioB_V_data_V_1_payload_B;
        else 
            AudioB_V_data_V_1_data_out <= AudioB_V_data_V_1_payload_A;
        end if; 
    end process;

    AudioB_V_data_V_1_load_A <= (not(AudioB_V_data_V_1_sel_wr) and AudioB_V_data_V_1_state_cmp_full);
    AudioB_V_data_V_1_load_B <= (AudioB_V_data_V_1_state_cmp_full and AudioB_V_data_V_1_sel_wr);
    AudioB_V_data_V_1_sel <= AudioB_V_data_V_1_sel_rd;
    AudioB_V_data_V_1_state_cmp_full <= '0' when (AudioB_V_data_V_1_state = ap_const_lv2_1) else '1';

    AudioB_V_data_V_1_vld_in_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioB_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            AudioB_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    AudioB_V_data_V_1_vld_out <= AudioB_V_data_V_1_state(0);
    AudioB_V_dest_V_1_ack_in <= AudioB_V_dest_V_1_state(1);
    AudioB_V_dest_V_1_ack_out <= AudioB_TREADY;

    AudioB_V_dest_V_1_data_out_assign_proc : process(AudioB_V_dest_V_1_payload_A, AudioB_V_dest_V_1_payload_B, AudioB_V_dest_V_1_sel)
    begin
        if ((ap_const_logic_1 = AudioB_V_dest_V_1_sel)) then 
            AudioB_V_dest_V_1_data_out <= AudioB_V_dest_V_1_payload_B;
        else 
            AudioB_V_dest_V_1_data_out <= AudioB_V_dest_V_1_payload_A;
        end if; 
    end process;

    AudioB_V_dest_V_1_load_A <= (not(AudioB_V_dest_V_1_sel_wr) and AudioB_V_dest_V_1_state_cmp_full);
    AudioB_V_dest_V_1_load_B <= (AudioB_V_dest_V_1_state_cmp_full and AudioB_V_dest_V_1_sel_wr);
    AudioB_V_dest_V_1_sel <= AudioB_V_dest_V_1_sel_rd;
    AudioB_V_dest_V_1_state_cmp_full <= '0' when (AudioB_V_dest_V_1_state = ap_const_lv2_1) else '1';

    AudioB_V_dest_V_1_vld_in_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioB_V_dest_V_1_vld_in <= ap_const_logic_1;
        else 
            AudioB_V_dest_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    AudioB_V_dest_V_1_vld_out <= AudioB_V_dest_V_1_state(0);
    AudioB_V_id_V_1_ack_in <= AudioB_V_id_V_1_state(1);
    AudioB_V_id_V_1_ack_out <= AudioB_TREADY;

    AudioB_V_id_V_1_data_out_assign_proc : process(AudioB_V_id_V_1_payload_A, AudioB_V_id_V_1_payload_B, AudioB_V_id_V_1_sel)
    begin
        if ((ap_const_logic_1 = AudioB_V_id_V_1_sel)) then 
            AudioB_V_id_V_1_data_out <= AudioB_V_id_V_1_payload_B;
        else 
            AudioB_V_id_V_1_data_out <= AudioB_V_id_V_1_payload_A;
        end if; 
    end process;

    AudioB_V_id_V_1_load_A <= (not(AudioB_V_id_V_1_sel_wr) and AudioB_V_id_V_1_state_cmp_full);
    AudioB_V_id_V_1_load_B <= (AudioB_V_id_V_1_state_cmp_full and AudioB_V_id_V_1_sel_wr);
    AudioB_V_id_V_1_sel <= AudioB_V_id_V_1_sel_rd;
    AudioB_V_id_V_1_state_cmp_full <= '0' when (AudioB_V_id_V_1_state = ap_const_lv2_1) else '1';

    AudioB_V_id_V_1_vld_in_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioB_V_id_V_1_vld_in <= ap_const_logic_1;
        else 
            AudioB_V_id_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    AudioB_V_id_V_1_vld_out <= AudioB_V_id_V_1_state(0);
    AudioB_V_keep_V_1_ack_in <= AudioB_V_keep_V_1_state(1);
    AudioB_V_keep_V_1_ack_out <= AudioB_TREADY;

    AudioB_V_keep_V_1_data_out_assign_proc : process(AudioB_V_keep_V_1_payload_A, AudioB_V_keep_V_1_payload_B, AudioB_V_keep_V_1_sel)
    begin
        if ((ap_const_logic_1 = AudioB_V_keep_V_1_sel)) then 
            AudioB_V_keep_V_1_data_out <= AudioB_V_keep_V_1_payload_B;
        else 
            AudioB_V_keep_V_1_data_out <= AudioB_V_keep_V_1_payload_A;
        end if; 
    end process;

    AudioB_V_keep_V_1_load_A <= (not(AudioB_V_keep_V_1_sel_wr) and AudioB_V_keep_V_1_state_cmp_full);
    AudioB_V_keep_V_1_load_B <= (AudioB_V_keep_V_1_state_cmp_full and AudioB_V_keep_V_1_sel_wr);
    AudioB_V_keep_V_1_sel <= AudioB_V_keep_V_1_sel_rd;
    AudioB_V_keep_V_1_state_cmp_full <= '0' when (AudioB_V_keep_V_1_state = ap_const_lv2_1) else '1';

    AudioB_V_keep_V_1_vld_in_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioB_V_keep_V_1_vld_in <= ap_const_logic_1;
        else 
            AudioB_V_keep_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    AudioB_V_keep_V_1_vld_out <= AudioB_V_keep_V_1_state(0);
    AudioB_V_last_V_1_ack_in <= AudioB_V_last_V_1_state(1);
    AudioB_V_last_V_1_ack_out <= AudioB_TREADY;

    AudioB_V_last_V_1_data_out_assign_proc : process(AudioB_V_last_V_1_payload_A, AudioB_V_last_V_1_payload_B, AudioB_V_last_V_1_sel)
    begin
        if ((ap_const_logic_1 = AudioB_V_last_V_1_sel)) then 
            AudioB_V_last_V_1_data_out <= AudioB_V_last_V_1_payload_B;
        else 
            AudioB_V_last_V_1_data_out <= AudioB_V_last_V_1_payload_A;
        end if; 
    end process;

    AudioB_V_last_V_1_load_A <= (not(AudioB_V_last_V_1_sel_wr) and AudioB_V_last_V_1_state_cmp_full);
    AudioB_V_last_V_1_load_B <= (AudioB_V_last_V_1_state_cmp_full and AudioB_V_last_V_1_sel_wr);
    AudioB_V_last_V_1_sel <= AudioB_V_last_V_1_sel_rd;
    AudioB_V_last_V_1_state_cmp_full <= '0' when (AudioB_V_last_V_1_state = ap_const_lv2_1) else '1';

    AudioB_V_last_V_1_vld_in_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioB_V_last_V_1_vld_in <= ap_const_logic_1;
        else 
            AudioB_V_last_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    AudioB_V_last_V_1_vld_out <= AudioB_V_last_V_1_state(0);
    AudioB_V_strb_V_1_ack_in <= AudioB_V_strb_V_1_state(1);
    AudioB_V_strb_V_1_ack_out <= AudioB_TREADY;

    AudioB_V_strb_V_1_data_out_assign_proc : process(AudioB_V_strb_V_1_payload_A, AudioB_V_strb_V_1_payload_B, AudioB_V_strb_V_1_sel)
    begin
        if ((ap_const_logic_1 = AudioB_V_strb_V_1_sel)) then 
            AudioB_V_strb_V_1_data_out <= AudioB_V_strb_V_1_payload_B;
        else 
            AudioB_V_strb_V_1_data_out <= AudioB_V_strb_V_1_payload_A;
        end if; 
    end process;

    AudioB_V_strb_V_1_load_A <= (not(AudioB_V_strb_V_1_sel_wr) and AudioB_V_strb_V_1_state_cmp_full);
    AudioB_V_strb_V_1_load_B <= (AudioB_V_strb_V_1_state_cmp_full and AudioB_V_strb_V_1_sel_wr);
    AudioB_V_strb_V_1_sel <= AudioB_V_strb_V_1_sel_rd;
    AudioB_V_strb_V_1_state_cmp_full <= '0' when (AudioB_V_strb_V_1_state = ap_const_lv2_1) else '1';

    AudioB_V_strb_V_1_vld_in_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioB_V_strb_V_1_vld_in <= ap_const_logic_1;
        else 
            AudioB_V_strb_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    AudioB_V_strb_V_1_vld_out <= AudioB_V_strb_V_1_state(0);
    AudioB_V_user_V_1_ack_in <= AudioB_V_user_V_1_state(1);
    AudioB_V_user_V_1_ack_out <= AudioB_TREADY;

    AudioB_V_user_V_1_data_out_assign_proc : process(AudioB_V_user_V_1_payload_A, AudioB_V_user_V_1_payload_B, AudioB_V_user_V_1_sel)
    begin
        if ((ap_const_logic_1 = AudioB_V_user_V_1_sel)) then 
            AudioB_V_user_V_1_data_out <= AudioB_V_user_V_1_payload_B;
        else 
            AudioB_V_user_V_1_data_out <= AudioB_V_user_V_1_payload_A;
        end if; 
    end process;

    AudioB_V_user_V_1_load_A <= (not(AudioB_V_user_V_1_sel_wr) and AudioB_V_user_V_1_state_cmp_full);
    AudioB_V_user_V_1_load_B <= (AudioB_V_user_V_1_state_cmp_full and AudioB_V_user_V_1_sel_wr);
    AudioB_V_user_V_1_sel <= AudioB_V_user_V_1_sel_rd;
    AudioB_V_user_V_1_state_cmp_full <= '0' when (AudioB_V_user_V_1_state = ap_const_lv2_1) else '1';

    AudioB_V_user_V_1_vld_in_assign_proc : process(AudioA_V_data_V_0_vld_out, AudioB_V_data_V_1_ack_in, ap_CS_fsm_state2)
    begin
        if ((not(((ap_const_logic_0 = AudioB_V_data_V_1_ack_in) or (ap_const_logic_0 = AudioA_V_data_V_0_vld_out))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            AudioB_V_user_V_1_vld_in <= ap_const_logic_1;
        else 
            AudioB_V_user_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    AudioB_V_user_V_1_vld_out <= AudioB_V_user_V_1_state(0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_done <= ap_const_logic_0;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

end behav;
