# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/hdl_projects/block_compile/block_compile.cache/wt [current_project]
set_property parent.project_path C:/hdl_projects/block_compile/block_compile.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/hdl_projects/digilent
  c:/hdl_projects/hls_lib
} [current_project]
set_property ip_output_repo c:/hdl_projects/block_compile/block_compile.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files C:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_dvi2rgb_1_1/src/ila_refclk/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_dvi2rgb_1_1/src/ila_refclk/ila_refclk_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_dvi2rgb_1_1/src/ila_timing_workaround.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_dvi2rgb_1_1/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_dvi2rgb_1_1/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_dvi2rgb_1_1/src/ila_pixclk/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_dvi2rgb_1_1/src/ila_pixclk/ila_pixclk_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_v_tc_1_0/design_1_v_tc_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_v_tc_1_0/design_1_v_tc_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_1/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_1/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_1/src/rgb2dvi_clocks.xdc]
set_property used_in_synthesis false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_1/design_1_v_tc_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_1/design_1_v_tc_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_synthesis false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/design_1_ila_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_3_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_3_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_3_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_3_0/design_1_ila_3_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_4_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_4_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_4_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_4_0/design_1_ila_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_0_1/design_1_axis_subset_converter_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_image_filter_0_0/constraints/image_filter_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_1_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_1_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_1_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_1_1/design_1_ila_1_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_5_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_5_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_5_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_ila_5_0/design_1_ila_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/hdl_projects/block_compile/block_compile.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/hdl_projects/block_compile/block_compile.srcs/constrs_1/new/cosnt.xdc
set_property used_in_implementation false [get_files C:/hdl_projects/block_compile/block_compile.srcs/constrs_1/new/cosnt.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
