// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "CvtColor_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic CvtColor_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic CvtColor_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> CvtColor_1::ap_ST_fsm_state1 = "1";
const sc_lv<4> CvtColor_1::ap_ST_fsm_state2 = "10";
const sc_lv<4> CvtColor_1::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> CvtColor_1::ap_ST_fsm_state8 = "1000";
const sc_lv<32> CvtColor_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool CvtColor_1::ap_const_boolean_1 = true;
const sc_lv<32> CvtColor_1::ap_const_lv32_2 = "10";
const bool CvtColor_1::ap_const_boolean_0 = false;
const sc_lv<1> CvtColor_1::ap_const_lv1_1 = "1";
const sc_lv<32> CvtColor_1::ap_const_lv32_1 = "1";
const sc_lv<1> CvtColor_1::ap_const_lv1_0 = "0";
const sc_lv<31> CvtColor_1::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> CvtColor_1::ap_const_lv32_3 = "11";
const sc_lv<31> CvtColor_1::ap_const_lv31_1 = "1";
const sc_lv<32> CvtColor_1::ap_const_lv32_16 = "10110";
const sc_lv<32> CvtColor_1::ap_const_lv32_1D = "11101";
const sc_lv<32> CvtColor_1::ap_const_lv32_15 = "10101";
const sc_lv<32> CvtColor_1::ap_const_lv32_7 = "111";
const sc_lv<8> CvtColor_1::ap_const_lv8_FF = "11111111";
const sc_lv<29> CvtColor_1::ap_const_lv29_1322D0 = "100110010001011010000";
const sc_lv<28> CvtColor_1::ap_const_lv28_74BC6 = "1110100101111000110";
const sc_lv<30> CvtColor_1::ap_const_lv30_259168 = "1001011001000101101000";

CvtColor_1::CvtColor_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    image_filter_mul_bkb_U23 = new image_filter_mul_bkb<1,1,22,8,29>("image_filter_mul_bkb_U23");
    image_filter_mul_bkb_U23->din0(r_V_4_i_i_fu_317_p0);
    image_filter_mul_bkb_U23->din1(r_V_4_i_i_fu_317_p1);
    image_filter_mul_bkb_U23->dout(r_V_4_i_i_fu_317_p2);
    image_filter_mac_cud_U24 = new image_filter_mac_cud<1,1,20,8,29,29>("image_filter_mac_cud_U24");
    image_filter_mac_cud_U24->din0(grp_fu_323_p0);
    image_filter_mac_cud_U24->din1(grp_fu_323_p1);
    image_filter_mac_cud_U24->din2(r_V_4_i_i_reg_384);
    image_filter_mac_cud_U24->dout(grp_fu_323_p3);
    image_filter_mac_dEe_U25 = new image_filter_mac_dEe<1,1,23,8,29,30>("image_filter_mac_dEe_U25");
    image_filter_mac_dEe_U25->din0(grp_fu_331_p0);
    image_filter_mac_dEe_U25->din1(grp_fu_331_p1);
    image_filter_mac_dEe_U25->din2(grp_fu_331_p2);
    image_filter_mac_dEe_U25->dout(grp_fu_331_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( p_src_data_stream_0_V_empty_n );
    sensitive << ( p_src_data_stream_1_V_empty_n );
    sensitive << ( p_src_data_stream_2_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_2_i_reg_360 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_2_i_reg_360_pp0_iter3_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( p_src_data_stream_0_V_empty_n );
    sensitive << ( p_src_data_stream_1_V_empty_n );
    sensitive << ( p_src_data_stream_2_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_2_i_reg_360 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_2_i_reg_360_pp0_iter3_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( p_src_data_stream_0_V_empty_n );
    sensitive << ( p_src_data_stream_1_V_empty_n );
    sensitive << ( p_src_data_stream_2_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_2_i_reg_360 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_2_i_reg_360_pp0_iter3_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( p_src_rows_V_empty_n );
    sensitive << ( p_src_cols_V_empty_n );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( p_src_data_stream_0_V_empty_n );
    sensitive << ( p_src_data_stream_1_V_empty_n );
    sensitive << ( p_src_data_stream_2_V_empty_n );
    sensitive << ( tmp_2_i_reg_360 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter4);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( tmp_2_i_reg_360_pp0_iter3_reg );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( tmp_2_i_fu_234_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( tmp_i_fu_219_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_i_fu_219_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_deleted_zeros_fu_302_p2);
    sensitive << ( tmp_4_fu_294_p3 );
    sensitive << ( rev_fu_288_p2 );

    SC_METHOD(thread_grp_fu_323_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_i_reg_360_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_grp_fu_323_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_i_reg_360_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( grp_fu_323_p10 );

    SC_METHOD(thread_grp_fu_323_p10);
    sensitive << ( tmp_6_reg_369_pp0_iter2_reg );

    SC_METHOD(thread_grp_fu_331_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_i_reg_360_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_grp_fu_331_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_i_reg_360_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( grp_fu_331_p10 );

    SC_METHOD(thread_grp_fu_331_p10);
    sensitive << ( tmp_7_reg_374_pp0_iter2_reg );

    SC_METHOD(thread_grp_fu_331_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_i_reg_360_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( grp_fu_331_p20 );

    SC_METHOD(thread_grp_fu_331_p20);
    sensitive << ( grp_fu_323_p3 );

    SC_METHOD(thread_i_cast_i_fu_215_p1);
    sensitive << ( i_i_reg_193 );

    SC_METHOD(thread_i_fu_224_p2);
    sensitive << ( i_i_reg_193 );

    SC_METHOD(thread_j_cast_i_fu_230_p1);
    sensitive << ( j_i_reg_204 );

    SC_METHOD(thread_j_fu_239_p2);
    sensitive << ( j_i_reg_204 );

    SC_METHOD(thread_p_Val2_4_fu_276_p2);
    sensitive << ( p_Val2_3_reg_394 );
    sensitive << ( tmp_8_i_i_i_cast_i_fu_273_p1 );

    SC_METHOD(thread_p_dst_data_stream_V_blk_n);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_2_i_reg_360_pp0_iter3_reg );

    SC_METHOD(thread_p_dst_data_stream_V_din);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_2_i_reg_360_pp0_iter3_reg );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( p_Val2_4_fu_276_p2 );
    sensitive << ( deleted_zeros_fu_302_p2 );

    SC_METHOD(thread_p_dst_data_stream_V_write);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_2_i_reg_360_pp0_iter3_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_src_cols_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_cols_V_empty_n );

    SC_METHOD(thread_p_src_cols_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_rows_V_empty_n );
    sensitive << ( p_src_cols_V_empty_n );

    SC_METHOD(thread_p_src_data_stream_0_V_blk_n);
    sensitive << ( p_src_data_stream_0_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_i_reg_360 );

    SC_METHOD(thread_p_src_data_stream_0_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_2_i_reg_360 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_src_data_stream_1_V_blk_n);
    sensitive << ( p_src_data_stream_1_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_i_reg_360 );

    SC_METHOD(thread_p_src_data_stream_1_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_2_i_reg_360 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_src_data_stream_2_V_blk_n);
    sensitive << ( p_src_data_stream_2_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_i_reg_360 );

    SC_METHOD(thread_p_src_data_stream_2_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_2_i_reg_360 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_src_rows_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_rows_V_empty_n );

    SC_METHOD(thread_p_src_rows_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_rows_V_empty_n );
    sensitive << ( p_src_cols_V_empty_n );

    SC_METHOD(thread_r_V_4_i_i_fu_317_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_r_V_4_i_i_fu_317_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( r_V_4_i_i_fu_317_p10 );

    SC_METHOD(thread_r_V_4_i_i_fu_317_p10);
    sensitive << ( tmp_8_reg_379 );

    SC_METHOD(thread_rev_fu_288_p2);
    sensitive << ( tmp_3_fu_281_p3 );

    SC_METHOD(thread_tmp_2_i_fu_234_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( cols_reg_341 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( j_cast_i_fu_230_p1 );

    SC_METHOD(thread_tmp_3_fu_281_p3);
    sensitive << ( ret_V_1_reg_389 );

    SC_METHOD(thread_tmp_4_fu_294_p3);
    sensitive << ( p_Val2_4_fu_276_p2 );

    SC_METHOD(thread_tmp_8_i_i_i_cast_i_fu_273_p1);
    sensitive << ( tmp_reg_399 );

    SC_METHOD(thread_tmp_i_fu_219_p2);
    sensitive << ( rows_reg_346 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_cast_i_fu_215_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_rows_V_empty_n );
    sensitive << ( p_src_cols_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_i_fu_219_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_2_i_fu_234_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "CvtColor_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_src_rows_V_dout, "(port)p_src_rows_V_dout");
    sc_trace(mVcdFile, p_src_rows_V_empty_n, "(port)p_src_rows_V_empty_n");
    sc_trace(mVcdFile, p_src_rows_V_read, "(port)p_src_rows_V_read");
    sc_trace(mVcdFile, p_src_cols_V_dout, "(port)p_src_cols_V_dout");
    sc_trace(mVcdFile, p_src_cols_V_empty_n, "(port)p_src_cols_V_empty_n");
    sc_trace(mVcdFile, p_src_cols_V_read, "(port)p_src_cols_V_read");
    sc_trace(mVcdFile, p_src_data_stream_0_V_dout, "(port)p_src_data_stream_0_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_0_V_empty_n, "(port)p_src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_0_V_read, "(port)p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, p_src_data_stream_1_V_dout, "(port)p_src_data_stream_1_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_1_V_empty_n, "(port)p_src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_1_V_read, "(port)p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, p_src_data_stream_2_V_dout, "(port)p_src_data_stream_2_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_2_V_empty_n, "(port)p_src_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_2_V_read, "(port)p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_V_din, "(port)p_dst_data_stream_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_V_full_n, "(port)p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_V_write, "(port)p_dst_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_src_rows_V_blk_n, "p_src_rows_V_blk_n");
    sc_trace(mVcdFile, p_src_cols_V_blk_n, "p_src_cols_V_blk_n");
    sc_trace(mVcdFile, p_src_data_stream_0_V_blk_n, "p_src_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_2_i_reg_360, "tmp_2_i_reg_360");
    sc_trace(mVcdFile, p_src_data_stream_1_V_blk_n, "p_src_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, p_src_data_stream_2_V_blk_n, "p_src_data_stream_2_V_blk_n");
    sc_trace(mVcdFile, p_dst_data_stream_V_blk_n, "p_dst_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, tmp_2_i_reg_360_pp0_iter3_reg, "tmp_2_i_reg_360_pp0_iter3_reg");
    sc_trace(mVcdFile, j_i_reg_204, "j_i_reg_204");
    sc_trace(mVcdFile, cols_reg_341, "cols_reg_341");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, rows_reg_346, "rows_reg_346");
    sc_trace(mVcdFile, tmp_i_fu_219_p2, "tmp_i_fu_219_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_224_p2, "i_fu_224_p2");
    sc_trace(mVcdFile, i_reg_355, "i_reg_355");
    sc_trace(mVcdFile, tmp_2_i_fu_234_p2, "tmp_2_i_fu_234_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter3, "ap_block_state6_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter4, "ap_block_state7_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, tmp_2_i_reg_360_pp0_iter1_reg, "tmp_2_i_reg_360_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_2_i_reg_360_pp0_iter2_reg, "tmp_2_i_reg_360_pp0_iter2_reg");
    sc_trace(mVcdFile, j_fu_239_p2, "j_fu_239_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_6_reg_369, "tmp_6_reg_369");
    sc_trace(mVcdFile, tmp_6_reg_369_pp0_iter2_reg, "tmp_6_reg_369_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_7_reg_374, "tmp_7_reg_374");
    sc_trace(mVcdFile, tmp_7_reg_374_pp0_iter2_reg, "tmp_7_reg_374_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_8_reg_379, "tmp_8_reg_379");
    sc_trace(mVcdFile, r_V_4_i_i_fu_317_p2, "r_V_4_i_i_fu_317_p2");
    sc_trace(mVcdFile, r_V_4_i_i_reg_384, "r_V_4_i_i_reg_384");
    sc_trace(mVcdFile, grp_fu_331_p3, "grp_fu_331_p3");
    sc_trace(mVcdFile, ret_V_1_reg_389, "ret_V_1_reg_389");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, p_Val2_3_reg_394, "p_Val2_3_reg_394");
    sc_trace(mVcdFile, tmp_reg_399, "tmp_reg_399");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, i_i_reg_193, "i_i_reg_193");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, i_cast_i_fu_215_p1, "i_cast_i_fu_215_p1");
    sc_trace(mVcdFile, j_cast_i_fu_230_p1, "j_cast_i_fu_230_p1");
    sc_trace(mVcdFile, grp_fu_323_p3, "grp_fu_323_p3");
    sc_trace(mVcdFile, tmp_8_i_i_i_cast_i_fu_273_p1, "tmp_8_i_i_i_cast_i_fu_273_p1");
    sc_trace(mVcdFile, tmp_3_fu_281_p3, "tmp_3_fu_281_p3");
    sc_trace(mVcdFile, p_Val2_4_fu_276_p2, "p_Val2_4_fu_276_p2");
    sc_trace(mVcdFile, tmp_4_fu_294_p3, "tmp_4_fu_294_p3");
    sc_trace(mVcdFile, rev_fu_288_p2, "rev_fu_288_p2");
    sc_trace(mVcdFile, deleted_zeros_fu_302_p2, "deleted_zeros_fu_302_p2");
    sc_trace(mVcdFile, r_V_4_i_i_fu_317_p0, "r_V_4_i_i_fu_317_p0");
    sc_trace(mVcdFile, r_V_4_i_i_fu_317_p1, "r_V_4_i_i_fu_317_p1");
    sc_trace(mVcdFile, grp_fu_323_p0, "grp_fu_323_p0");
    sc_trace(mVcdFile, grp_fu_323_p1, "grp_fu_323_p1");
    sc_trace(mVcdFile, grp_fu_331_p0, "grp_fu_331_p0");
    sc_trace(mVcdFile, grp_fu_331_p1, "grp_fu_331_p1");
    sc_trace(mVcdFile, grp_fu_331_p2, "grp_fu_331_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_323_p10, "grp_fu_323_p10");
    sc_trace(mVcdFile, grp_fu_331_p10, "grp_fu_331_p10");
    sc_trace(mVcdFile, grp_fu_331_p20, "grp_fu_331_p20");
    sc_trace(mVcdFile, r_V_4_i_i_fu_317_p10, "r_V_4_i_i_fu_317_p10");
#endif

    }
}

CvtColor_1::~CvtColor_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete image_filter_mul_bkb_U23;
    delete image_filter_mac_cud_U24;
    delete image_filter_mac_dEe_U25;
}

void CvtColor_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(tmp_i_fu_219_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_fu_219_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_fu_219_p2.read()))) {
            ap_enable_reg_pp0_iter4 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_i_reg_193 = i_reg_355.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_rows_V_empty_n.read())))) {
        i_i_reg_193 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_i_fu_234_p2.read()))) {
        j_i_reg_204 = j_fu_239_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_fu_219_p2.read()))) {
        j_i_reg_204 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_rows_V_empty_n.read())))) {
        cols_reg_341 = p_src_cols_V_dout.read();
        rows_reg_346 = p_src_rows_V_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_355 = i_fu_224_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_i_reg_360_pp0_iter2_reg.read()))) {
        p_Val2_3_reg_394 = grp_fu_331_p3.read().range(29, 22);
        tmp_reg_399 = grp_fu_331_p3.read().range(21, 21);
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_i_reg_360_pp0_iter1_reg.read()))) {
        r_V_4_i_i_reg_384 = r_V_4_i_i_fu_317_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_i_reg_360_pp0_iter2_reg.read()))) {
        ret_V_1_reg_389 = grp_fu_331_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_2_i_reg_360 = tmp_2_i_fu_234_p2.read();
        tmp_2_i_reg_360_pp0_iter1_reg = tmp_2_i_reg_360.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        tmp_2_i_reg_360_pp0_iter2_reg = tmp_2_i_reg_360_pp0_iter1_reg.read();
        tmp_2_i_reg_360_pp0_iter3_reg = tmp_2_i_reg_360_pp0_iter2_reg.read();
        tmp_6_reg_369_pp0_iter2_reg = tmp_6_reg_369.read();
        tmp_7_reg_374_pp0_iter2_reg = tmp_7_reg_374.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_6_reg_369 = p_src_data_stream_0_V_dout.read();
        tmp_7_reg_374 = p_src_data_stream_1_V_dout.read();
        tmp_8_reg_379 = p_src_data_stream_2_V_dout.read();
    }
}

void CvtColor_1::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void CvtColor_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void CvtColor_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void CvtColor_1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[3];
}

void CvtColor_1::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CvtColor_1::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
    esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_0_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
    esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_1_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
    esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_2_V_empty_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_i_reg_360_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void CvtColor_1::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
    esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_0_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
    esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_1_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
    esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_2_V_empty_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_i_reg_360_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void CvtColor_1::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
    esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_0_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
    esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_1_V_empty_n.read())) || 
   (esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
    esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_2_V_empty_n.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_i_reg_360_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void CvtColor_1::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_rows_V_empty_n.read()));
}

void CvtColor_1::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CvtColor_1::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = ((esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_0_V_empty_n.read())) || (esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_1_V_empty_n.read())) || (esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_2_V_empty_n.read())));
}

void CvtColor_1::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CvtColor_1::thread_ap_block_state6_pp0_stage0_iter3() {
    ap_block_state6_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CvtColor_1::thread_ap_block_state7_pp0_stage0_iter4() {
    ap_block_state7_pp0_stage0_iter4 = (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_i_reg_360_pp0_iter3_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read()));
}

void CvtColor_1::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(tmp_2_i_fu_234_p2.read(), ap_const_lv1_0)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void CvtColor_1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_i_fu_219_p2.read(), ap_const_lv1_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void CvtColor_1::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void CvtColor_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void CvtColor_1::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void CvtColor_1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_i_fu_219_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void CvtColor_1::thread_deleted_zeros_fu_302_p2() {
    deleted_zeros_fu_302_p2 = (tmp_4_fu_294_p3.read() | rev_fu_288_p2.read());
}

void CvtColor_1::thread_grp_fu_323_p0() {
    grp_fu_323_p0 =  (sc_lv<20>) (ap_const_lv28_74BC6);
}

void CvtColor_1::thread_grp_fu_323_p1() {
    grp_fu_323_p1 =  (sc_lv<8>) (grp_fu_323_p10.read());
}

void CvtColor_1::thread_grp_fu_323_p10() {
    grp_fu_323_p10 = esl_zext<28,8>(tmp_6_reg_369_pp0_iter2_reg.read());
}

void CvtColor_1::thread_grp_fu_331_p0() {
    grp_fu_331_p0 =  (sc_lv<23>) (ap_const_lv30_259168);
}

void CvtColor_1::thread_grp_fu_331_p1() {
    grp_fu_331_p1 =  (sc_lv<8>) (grp_fu_331_p10.read());
}

void CvtColor_1::thread_grp_fu_331_p10() {
    grp_fu_331_p10 = esl_zext<30,8>(tmp_7_reg_374_pp0_iter2_reg.read());
}

void CvtColor_1::thread_grp_fu_331_p2() {
    grp_fu_331_p2 =  (sc_lv<29>) (grp_fu_331_p20.read());
}

void CvtColor_1::thread_grp_fu_331_p20() {
    grp_fu_331_p20 = esl_zext<30,29>(grp_fu_323_p3.read());
}

void CvtColor_1::thread_i_cast_i_fu_215_p1() {
    i_cast_i_fu_215_p1 = esl_zext<32,31>(i_i_reg_193.read());
}

void CvtColor_1::thread_i_fu_224_p2() {
    i_fu_224_p2 = (!i_i_reg_193.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(i_i_reg_193.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void CvtColor_1::thread_j_cast_i_fu_230_p1() {
    j_cast_i_fu_230_p1 = esl_zext<32,31>(j_i_reg_204.read());
}

void CvtColor_1::thread_j_fu_239_p2() {
    j_fu_239_p2 = (!j_i_reg_204.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(j_i_reg_204.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void CvtColor_1::thread_p_Val2_4_fu_276_p2() {
    p_Val2_4_fu_276_p2 = (!tmp_8_i_i_i_cast_i_fu_273_p1.read().is_01() || !p_Val2_3_reg_394.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_8_i_i_i_cast_i_fu_273_p1.read()) + sc_biguint<8>(p_Val2_3_reg_394.read()));
}

void CvtColor_1::thread_p_dst_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_i_reg_360_pp0_iter3_reg.read()))) {
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n.read();
    } else {
        p_dst_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void CvtColor_1::thread_p_dst_data_stream_V_din() {
    p_dst_data_stream_V_din = (!deleted_zeros_fu_302_p2.read()[0].is_01())? sc_lv<8>(): ((deleted_zeros_fu_302_p2.read()[0].to_bool())? p_Val2_4_fu_276_p2.read(): ap_const_lv8_FF);
}

void CvtColor_1::thread_p_dst_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_i_reg_360_pp0_iter3_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_dst_data_stream_V_write = ap_const_logic_1;
    } else {
        p_dst_data_stream_V_write = ap_const_logic_0;
    }
}

void CvtColor_1::thread_p_src_cols_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_src_cols_V_blk_n = p_src_cols_V_empty_n.read();
    } else {
        p_src_cols_V_blk_n = ap_const_logic_1;
    }
}

void CvtColor_1::thread_p_src_cols_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_rows_V_empty_n.read())))) {
        p_src_cols_V_read = ap_const_logic_1;
    } else {
        p_src_cols_V_read = ap_const_logic_0;
    }
}

void CvtColor_1::thread_p_src_data_stream_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1))) {
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n.read();
    } else {
        p_src_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void CvtColor_1::thread_p_src_data_stream_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_src_data_stream_0_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_0_V_read = ap_const_logic_0;
    }
}

void CvtColor_1::thread_p_src_data_stream_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1))) {
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n.read();
    } else {
        p_src_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void CvtColor_1::thread_p_src_data_stream_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_src_data_stream_1_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_1_V_read = ap_const_logic_0;
    }
}

void CvtColor_1::thread_p_src_data_stream_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1))) {
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n.read();
    } else {
        p_src_data_stream_2_V_blk_n = ap_const_logic_1;
    }
}

void CvtColor_1::thread_p_src_data_stream_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_2_i_reg_360.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_src_data_stream_2_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_2_V_read = ap_const_logic_0;
    }
}

void CvtColor_1::thread_p_src_rows_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_src_rows_V_blk_n = p_src_rows_V_empty_n.read();
    } else {
        p_src_rows_V_blk_n = ap_const_logic_1;
    }
}

void CvtColor_1::thread_p_src_rows_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_rows_V_empty_n.read())))) {
        p_src_rows_V_read = ap_const_logic_1;
    } else {
        p_src_rows_V_read = ap_const_logic_0;
    }
}

void CvtColor_1::thread_r_V_4_i_i_fu_317_p0() {
    r_V_4_i_i_fu_317_p0 =  (sc_lv<22>) (ap_const_lv29_1322D0);
}

void CvtColor_1::thread_r_V_4_i_i_fu_317_p1() {
    r_V_4_i_i_fu_317_p1 =  (sc_lv<8>) (r_V_4_i_i_fu_317_p10.read());
}

void CvtColor_1::thread_r_V_4_i_i_fu_317_p10() {
    r_V_4_i_i_fu_317_p10 = esl_zext<29,8>(tmp_8_reg_379.read());
}

void CvtColor_1::thread_rev_fu_288_p2() {
    rev_fu_288_p2 = (tmp_3_fu_281_p3.read() ^ ap_const_lv1_1);
}

void CvtColor_1::thread_tmp_2_i_fu_234_p2() {
    tmp_2_i_fu_234_p2 = (!j_cast_i_fu_230_p1.read().is_01() || !cols_reg_341.read().is_01())? sc_lv<1>(): (sc_bigint<32>(j_cast_i_fu_230_p1.read()) < sc_bigint<32>(cols_reg_341.read()));
}

void CvtColor_1::thread_tmp_3_fu_281_p3() {
    tmp_3_fu_281_p3 = ret_V_1_reg_389.read().range(29, 29);
}

void CvtColor_1::thread_tmp_4_fu_294_p3() {
    tmp_4_fu_294_p3 = p_Val2_4_fu_276_p2.read().range(7, 7);
}

void CvtColor_1::thread_tmp_8_i_i_i_cast_i_fu_273_p1() {
    tmp_8_i_i_i_cast_i_fu_273_p1 = esl_zext<8,1>(tmp_reg_399.read());
}

void CvtColor_1::thread_tmp_i_fu_219_p2() {
    tmp_i_fu_219_p2 = (!i_cast_i_fu_215_p1.read().is_01() || !rows_reg_346.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i_cast_i_fu_215_p1.read()) < sc_bigint<32>(rows_reg_346.read()));
}

void CvtColor_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, p_src_rows_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_i_fu_219_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(tmp_2_i_fu_234_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(tmp_2_i_fu_234_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

